import { KittyConfig } from "@/lib/types";
import { ANSI_COLOR_LABELS } from "./schema";

function sanitizeValue(value: string): string {
  return value.replace(/[\n\r]/g, "").trim();
}

export function generateKittyConf(config: KittyConfig): string {
  const lines: string[] = [];

  lines.push("# Generated by Konfig — https://konfig.app");
  lines.push(`# Theme: ${config.activePreset || "Custom"}`);
  lines.push("");

  // --- Colors ---
  lines.push("# --- Colors & Theme ---");
  lines.push("");
  lines.push("# Main foreground (text) color");
  lines.push(`foreground ${sanitizeValue(config.colors.foreground)}`);
  lines.push("");
  lines.push("# Main background color");
  lines.push(`background ${sanitizeValue(config.colors.background)}`);
  lines.push("");
  lines.push("# Selection colors");
  lines.push(`selection_foreground ${sanitizeValue(config.colors.selection_foreground)}`);
  lines.push(`selection_background ${sanitizeValue(config.colors.selection_background)}`);
  lines.push("");
  lines.push("# Cursor colors");
  lines.push(`cursor ${sanitizeValue(config.colors.cursor)}`);
  lines.push(`cursor_text_color ${sanitizeValue(config.colors.cursor_text_color)}`);

  const cursorShapeMap = { block: "block", beam: "beam", underline: "underline" };
  lines.push(`cursor_shape ${cursorShapeMap[config.cursor_style]}`);
  lines.push("");

  lines.push("# URL color");
  lines.push(`url_color ${sanitizeValue(config.colors.url_color)}`);
  lines.push("");

  lines.push("# ANSI color palette");
  for (let i = 0; i <= 15; i++) {
    const key = `color${i}` as keyof typeof config.colors;
    const label = ANSI_COLOR_LABELS[key] || `Color ${i}`;
    lines.push(`# ${label}`);
    lines.push(`color${i} ${sanitizeValue(config.colors[key])}`);
  }
  lines.push("");

  // --- Font & Text ---
  lines.push("# --- Font & Text ---");
  lines.push("");
  lines.push("# Primary font family");
  lines.push(`font_family ${sanitizeValue(config.font.font_family)}`);
  lines.push("");
  lines.push("# Font size in points");
  lines.push(`font_size ${config.font.font_size}`);
  lines.push("");

  if (config.font.bold_font !== "auto") {
    lines.push(`bold_font ${sanitizeValue(config.font.bold_font)}`);
  } else {
    lines.push("bold_font auto");
  }
  if (config.font.italic_font !== "auto") {
    lines.push(`italic_font ${sanitizeValue(config.font.italic_font)}`);
  } else {
    lines.push("italic_font auto");
  }
  if (config.font.bold_italic_font !== "auto") {
    lines.push(`bold_italic_font ${sanitizeValue(config.font.bold_italic_font)}`);
  } else {
    lines.push("bold_italic_font auto");
  }
  lines.push("");

  lines.push("# Line height (multiplier)");
  lines.push(`adjust_line_height ${config.font.adjust_line_height}`);
  if (config.font.adjust_column_width !== 0) {
    lines.push(`adjust_column_width ${config.font.adjust_column_width}`);
  }
  lines.push("");

  lines.push(`disable_ligatures ${config.font.disable_ligatures}`);
  lines.push(`box_drawing_scale ${config.font.box_drawing_scale}`);
  lines.push("");

  // --- Window & Layout ---
  lines.push("# --- Window & Layout ---");
  lines.push("");
  lines.push("# Padding inside the terminal window (in pts)");
  lines.push(`window_padding_width ${config.window.window_padding_width}`);
  lines.push("");
  lines.push("# Margin around the terminal window");
  lines.push(`window_margin_width ${config.window.window_margin_width}`);
  lines.push("");
  lines.push("# Background transparency (1.0 = fully opaque)");
  lines.push(`background_opacity ${config.window.background_opacity.toFixed(2)}`);
  lines.push("");
  lines.push("# Window decoration style");
  lines.push(`window_decorations ${config.window.window_decorations}`);
  lines.push("");
  lines.push("# Initial terminal size in columns x rows");
  lines.push(`remember_window_size no`);
  lines.push(`initial_window_width ${config.window.initial_window_width}c`);
  lines.push(`initial_window_height ${config.window.initial_window_height}c`);
  lines.push("");
  lines.push(`resize_debounce_time ${config.window.resize_debounce_time / 1000}`);
  if (config.window.hide_window_decorations_on_tile) {
    lines.push("hide_window_decorations yes");
  }
  lines.push("");

  // --- Performance & Behavior ---
  lines.push("# --- Performance & Behavior ---");
  lines.push("");
  lines.push("# Time between screen redraws (ms)");
  lines.push(`repaint_delay ${config.performance.repaint_delay}`);
  lines.push("");
  lines.push("# Delay before processing input (ms)");
  lines.push(`input_delay ${config.performance.input_delay}`);
  lines.push("");
  lines.push(`sync_to_monitor ${config.performance.sync_to_monitor ? "yes" : "no"}`);
  lines.push("");
  lines.push("# Bell settings");
  lines.push(`enable_audio_bell ${config.performance.enable_audio_bell ? "yes" : "no"}`);
  lines.push(`visual_bell_duration ${config.performance.visual_bell_duration.toFixed(1)}`);
  lines.push("");
  lines.push(`mouse_hide_wait ${config.performance.mouse_hide_wait.toFixed(1)}`);
  lines.push(`copy_on_select ${config.performance.copy_on_select ? "yes" : "no"}`);
  lines.push(`focus_follows_mouse ${config.performance.focus_follows_mouse ? "yes" : "no"}`);
  lines.push("");
  lines.push("# Number of lines of scrollback history");
  lines.push(`scrollback_lines ${config.performance.scrollback_lines}`);
  lines.push("");
  if (config.performance.open_url_with !== "default") {
    lines.push(`open_url_with ${sanitizeValue(config.performance.open_url_with)}`);
    lines.push("");
  }

  // --- Shell & Startup ---
  lines.push("# --- Shell & Startup ---");
  lines.push("");
  lines.push("# Shell program to run");
  lines.push(`shell ${sanitizeValue(config.shell.shell)}`);
  lines.push("");
  lines.push("# Text editor");
  lines.push(`editor ${sanitizeValue(config.shell.editor)}`);
  lines.push("");
  if (config.shell.shell_integration.length > 0) {
    lines.push(`shell_integration no-${config.shell.shell_integration.join(" no-")}`);
    lines.push("");
  }
  if (config.shell.startup_session !== "none") {
    lines.push(`startup_session ${sanitizeValue(config.shell.startup_session)}`);
    lines.push("");
  }
  lines.push(`close_on_child_death ${config.shell.close_on_child_death ? "yes" : "no"}`);
  lines.push("");

  // --- Keyboard Shortcuts ---
  lines.push("# --- Keyboard Shortcuts ---");
  lines.push("");
  const actionToKittyMap: Record<string, string> = {
    "New tab": "new_tab",
    "Close tab": "close_tab",
    "Next tab": "next_tab",
    "Previous tab": "previous_tab",
    "New window": "new_window",
    "Close window": "close_window",
    "Scroll up": "scroll_line_up",
    "Scroll down": "scroll_line_down",
    "Scroll page up": "scroll_page_up",
    "Scroll page down": "scroll_page_down",
    "Increase font size": "change_font_size all +2.0",
    "Decrease font size": "change_font_size all -2.0",
    "Reset font size": "change_font_size all 0",
    "Copy to clipboard": "copy_to_clipboard",
    "Paste from clipboard": "paste_from_clipboard",
  };

  for (const shortcut of config.shortcuts) {
    const kittyAction = actionToKittyMap[shortcut.action] || shortcut.action;
    const key = sanitizeValue(shortcut.key);
    lines.push(`map ${key} ${kittyAction}`);
  }
  lines.push("");

  return lines.join("\n");
}
