import { KittyConfig, KittyShortcut } from "@/lib/types";

export const ANSI_COLOR_LABELS: Record<string, string> = {
  color0: "Black",
  color1: "Red",
  color2: "Green",
  color3: "Yellow",
  color4: "Blue",
  color5: "Magenta",
  color6: "Cyan",
  color7: "White",
  color8: "Bright Black",
  color9: "Bright Red",
  color10: "Bright Green",
  color11: "Bright Yellow",
  color12: "Bright Blue",
  color13: "Bright Magenta",
  color14: "Bright Cyan",
  color15: "Bright White",
};

export const FONT_OPTIONS = [
  "JetBrains Mono",
  "Fira Code",
  "Roboto Mono",
  "Cascadia Code",
  "Inconsolata",
  "Source Code Pro",
  "IBM Plex Mono",
  "Ubuntu Mono",
];

export const SHELL_OPTIONS = ["bash", "zsh", "fish", "sh"];
export const EDITOR_OPTIONS = ["vim", "nvim", "nano", "emacs"];
export const SHELL_INTEGRATION_OPTIONS = [
  "no-cursor",
  "no-title",
  "no-cwd",
  "no-prompt-mark",
  "no-complete",
  "no-sudo",
];

export const DEFAULT_SHORTCUTS: KittyShortcut[] = [
  { id: "new_tab", action: "New tab", key: "ctrl+shift+t" },
  { id: "close_tab", action: "Close tab", key: "ctrl+shift+q" },
  { id: "next_tab", action: "Next tab", key: "ctrl+shift+right" },
  { id: "prev_tab", action: "Previous tab", key: "ctrl+shift+left" },
  { id: "new_window", action: "New window", key: "ctrl+shift+enter" },
  { id: "close_window", action: "Close window", key: "ctrl+shift+w" },
  { id: "scroll_up", action: "Scroll up", key: "ctrl+shift+up" },
  { id: "scroll_down", action: "Scroll down", key: "ctrl+shift+down" },
  { id: "scroll_page_up", action: "Scroll page up", key: "ctrl+shift+page_up" },
  { id: "scroll_page_down", action: "Scroll page down", key: "ctrl+shift+page_down" },
  { id: "increase_font", action: "Increase font size", key: "ctrl+shift+equal" },
  { id: "decrease_font", action: "Decrease font size", key: "ctrl+shift+minus" },
  { id: "reset_font", action: "Reset font size", key: "ctrl+shift+backspace" },
  { id: "copy", action: "Copy to clipboard", key: "ctrl+shift+c" },
  { id: "paste", action: "Paste from clipboard", key: "ctrl+shift+v" },
];

export const defaultConfig: KittyConfig = {
  colors: {
    foreground: "#c0caf5",
    background: "#1a1b26",
    selection_foreground: "#c0caf5",
    selection_background: "#33467c",
    cursor: "#c0caf5",
    cursor_text_color: "#1a1b26",
    url_color: "#73daca",
    color0: "#15161e",
    color1: "#f7768e",
    color2: "#9ece6a",
    color3: "#e0af68",
    color4: "#7aa2f7",
    color5: "#bb9af7",
    color6: "#7dcfff",
    color7: "#a9b1d6",
    color8: "#414868",
    color9: "#f7768e",
    color10: "#9ece6a",
    color11: "#e0af68",
    color12: "#7aa2f7",
    color13: "#bb9af7",
    color14: "#7dcfff",
    color15: "#c0caf5",
  },
  cursor_style: "block",
  font: {
    font_family: "JetBrains Mono",
    font_size: 13,
    bold_font: "auto",
    italic_font: "auto",
    bold_italic_font: "auto",
    disable_ligatures: "never",
    adjust_line_height: 1.2,
    adjust_column_width: 0,
    box_drawing_scale: "0.001, 1, 1.5, 2",
  },
  shortcuts: [...DEFAULT_SHORTCUTS],
  window: {
    window_padding_width: 10,
    window_margin_width: 0,
    background_opacity: 1.0,
    window_decorations: "full",
    initial_window_width: 100,
    initial_window_height: 35,
    resize_debounce_time: 100,
    hide_window_decorations_on_tile: false,
  },
  performance: {
    repaint_delay: 10,
    input_delay: 3,
    sync_to_monitor: true,
    enable_audio_bell: true,
    visual_bell_duration: 0,
    mouse_hide_wait: 3,
    copy_on_select: false,
    focus_follows_mouse: false,
    scrollback_lines: 2000,
    open_url_with: "default",
  },
  shell: {
    shell: ".",
    editor: ".",
    shell_integration: [],
    startup_session: "none",
    close_on_child_death: false,
  },
  activePreset: "tokyo-night",
};

export const SETTING_DESCRIPTIONS: Record<string, string> = {
  foreground: "The default text color in the terminal",
  background: "The terminal background color",
  selection_foreground: "Text color when selected",
  selection_background: "Background color of selected text",
  cursor: "The color of the terminal cursor",
  cursor_text_color: "Color of text under the cursor",
  cursor_style: "Shape of the cursor: block, beam (thin line), or underline",
  url_color: "Color of detected URLs in the terminal",
  font_family: "The main font used for terminal text",
  font_size: "Size of the terminal font in points",
  bold_font: "Font used for bold text (auto uses the bold variant of your font)",
  italic_font: "Font used for italic text",
  adjust_line_height: "Space between lines of text",
  adjust_column_width: "Extra horizontal spacing between characters",
  box_drawing_scale: "Thickness scale for box-drawing characters",
  window_padding_width: "Space between terminal content and the window edge",
  window_margin_width: "Outer margin around the terminal window",
  background_opacity: "Transparency of the terminal background (1.0 = fully opaque)",
  window_decorations: "Controls the visibility of the window title bar and borders",
  initial_window_width: "Number of columns when the terminal first opens",
  initial_window_height: "Number of rows when the terminal first opens",
  resize_debounce_time: "Delay before applying window resize (in ms)",
  hide_window_decorations_on_tile: "Hide title bar when window is tiled",
  repaint_delay: "Time between screen redraws in milliseconds (lower = smoother)",
  input_delay: "Delay before processing keyboard input in milliseconds",
  sync_to_monitor: "Sync rendering to your monitor's refresh rate",
  enable_audio_bell: "Play a sound when the terminal bell triggers",
  visual_bell_duration: "Duration of the visual flash for the bell (0 = disabled)",
  mouse_hide_wait: "Seconds before hiding the mouse cursor while typing",
  copy_on_select: "Automatically copy text to clipboard when selected",
  focus_follows_mouse: "Focus switches to terminal window when mouse enters it",
  scrollback_lines: "Number of lines kept in the scroll-back buffer",
  open_url_with: "Program used to open URLs (default = system browser)",
  shell: "The shell program to run (. = use system default)",
  editor: "The text editor to use (. = use system default)",
  shell_integration: "Features to disable from Kitty's shell integration",
  startup_session: "Path to a session file to load on startup",
  close_on_child_death: "Close the terminal when the shell process exits",
};

export const BEGINNER_HIDDEN_SETTINGS = [
  "box_drawing_scale",
  "disable_ligatures",
  "bold_italic_font",
  "resize_debounce_time",
  "hide_window_decorations_on_tile",
  "repaint_delay",
  "input_delay",
  "sync_to_monitor",
  "visual_bell_duration",
  "mouse_hide_wait",
  "focus_follows_mouse",
  "open_url_with",
  "shell_integration",
  "startup_session",
  "close_on_child_death",
  "selection_foreground",
  "selection_background",
  "cursor_text_color",
  "url_color",
  "adjust_column_width",
  "window_margin_width",
];
